name: Build libzim on Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install packages
        run:
          choco install ninja
          
      - name: Install python modules
        run: pip3 install meson
        
      - name: Compile
        shell: cmd
        run: .github\script\build_libzim.cmd
        
      - name: Test
        shell: cmd
        run: |
          cd build
          ninja download_test_data
          meson test --verbose

      - uses: actions/upload-artifact@v2
        with:
          name: "libzim"
          path: "build"
